name: Main branch PR                                                                                                                                                                                                             

on:                                                                                                                   
    pull_request:                                                                                                       
      branches: [ "main" ]                                                                                              
                                                                                                                        
jobs:                                                                                                                 
                                                                                                                        
    deploy:                                                                                                             
      name: Deploy bundle                                                                                               
      runs-on: ubuntu-latest                                                                                            
                                                                                                                        
      environment: prod_env                                                                                             
      env:                                                                                                              
        #DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}                                                                   
        DATABRICKS_CLIENT_ID: ${{secrets.DATABRICKS_CLIENT_ID}}                                                         
        DATABRICKS_CLIENT_SECRET: ${{secrets.DATABRICKS_CLIENT_SECRET}}                                                 
        BUNDLE_VAR_catalog: ${{vars.CATALOG}}                                                                           
        BUNDLE_VAR_schema: ${{vars.SCHEMA}} 
                                                                            
      # Checkout code, setup databricks CLI and then, deploy the bundle using DABs                                      
      steps:                                                                                                            
        - uses: actions/checkout@v3                                                                                     
        - uses: databricks/setup-cli@main                                                                               
                                                                                                                        
        -   run: |                                                                                                      
              cd dabs_project                                                                                            
              databricks bundle deploy -t prod  
